### ISSUE TITLE
Colour Contrast Checker won't launch in Brave

### ISSUE THREAD

**Issue by gavinwye** [Pushedskydiver/Colour-Contrast-Checker#17] opened 2020-11-23 16:29 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behaviour?**

It's not working

**If the current behaviour is a bug, please provide the steps to reproduce.**

Click the icon nothing happens in Brave `Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)`

**What is the expected behaviour?**

The panel should launch

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version
- Browser

**Comment by Pushedskydiver** [comment] 2020-11-27 23:04
Hey @gavinwye thank you for raising this. I have had a look into this and can see the issue is related to local storage. I am currently in the middle of converting this app to use TypeScript so can look into your issue at the same time.

**Comment by Pushedskydiver** [comment] 2024-06-29 17:13
Going to close this as in the next release of the browser extension this issue will be resolved.

**Closed by Pushedskydiver** 2024-06-29 17:13 UTC
Labels: bug
